services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: mysql://root:password@db:3306/symfony
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"

  apache:
    image: php:8.2-apache
    container_name: symfony-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      APP_SECRET: 176961b8eced9a40ccbf9835a8eac711
    depends_on:
      - db