services:
  # Service PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - php:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  apache:
    image: httpd:2.4
    depends_on:
      - php
    volumes:
      - ./apache/symfony.conf:/usr/local/apache-1/conf/httpd.conf
      - php:/var/www/html
    ports:
      - "8082:80"
    networks:
      - app-network

  # Service MySQL
  mysql:
    image: mysql:8.0 
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  # Service PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony

  # Service MailPit
  mailpit:
    image: axllent/mailpit
    networks:
      - app-network
    ports:
      - "8025:8025"
    volumes:
      - mailpit:/data

  # Service Node
  node:
    image: node:18
    volumes:
      - node:/usr/src/app
    networks:
      - app-network
    working_dir: /usr/src/app
    command: tail -f /dev/null

volumes:
  php:
  apache:
  mysql:
  mailpit:
  node:

networks:
  app-network:
    driver: bridge
