services:
  # Service PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    expose:
      - 9000

  # Service Apache
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./public:/var/www/html/public
      

  # Service MySQL
  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  # Service PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony

  # Service MailPit
  mailpit:
    image: axllent/mailpit
    networks:
      - app-network
    ports:
      - "8025:8025"
    volumes:
      - mailpit:/data

  # Service Node
  node:
    image: node:18
    volumes:
      - node:/usr/src/app
    networks:
      - app-network
    working_dir: /usr/src/app
    command: tail -f /dev/null

volumes:
  php:
  apache:
  mysql:
  mailpit:
  node:

networks:
  app-network:
    driver: bridge