FROM httpd:2.4

# Copier le fichier symfony.conf dans le répertoire extra
COPY ./apache/symfony.conf /usr/local/apache2/conf/extra/symfony.conf

# Ajouter une directive Include dans httpd.conf
RUN echo "Include conf/extra/symfony.conf" >> /usr/local/apache2/conf/httpd.conf

# Activer le module rewrite
RUN sed -i '/LoadModule rewrite_module/s/^#//g' /usr/local/apache2/conf/httpd.conf

RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

